 			<form >
  			<select name="ward">
  			<option value="All Wards" selected>All Wards</option>	
			<option value="1">Ward 1, Renal Inpatients</option>
			<option value="2">Ward 2, AMC</option>
			<option value="4ATR">Ward 4 - AT&R</option>		
			<option value="5">Ward 5 - AT&R</option>
			<option value="6S">Ward 6 - STROKE</option>				
			<option value="7">Ward 7 Adult Medical Centre</option>
			<option value="8">Ward 8 Surgical</option>
			<option value="9">Ward 9 Surgical</option>
			<option value="10">Ward 10 Orthopaedic</option>
			<option value="11">Ward 11 Orthopaedic</option>
			<option value="23">Ward 23</option>
			<option value="24">Ward 24</option>
			<option value="31 DL">Ward 31-DISCHARGE LOUNGE</option>
			<option value="32N">Ward 32 - North</option>
			<option value="33E">Ward 33 - East</option>
			<option value="33N">Ward 33 - North</option>
			<option value="34E">Ward 34 - East</option>
			<option value="34N">Ward 34 - North</option>
			<option value="35E">WARD 35 EAST</option>
			<option value="35N">WARD 35 NORTH - PLASTICS</option>
			<option value="ALBN">Birthing & Assessment - North</option>
			<option value="ALBS">Birthing & Assessment - South</option>
			<option value="ALLH">ACUTE ALLIED HEALTH</option>
			<option value="ANT">Antenatal Clinic</option>
			<option value="AOU">ASSESSMENT OBSERVATION UNIT (AOU)</option>
			<option value="AWH">AWHINITIA COMMUNITY HEALTH</option>
			<option value="BDS">Botany Rd Superclinic</option>
			<option value="BOTO">Botany Rd Maternity Hospital</option>
			<option value="BREA">Breast Clinic</option>
			<option value="BRSC">Breast Screening Manukau Superclini</option>
			<option value="CALLC">Manukau Superclinic Call Centre</option>
			<option value="CAPD">Cont Ambulatory Peritoneal Dialysis</option>
			<option value="CARD">Cardiac Investigation Unit</option>
			<option value="CAST">Casting Unit</option>
			<option value="CATT">Community Assessment and Treatment</option>
			<option value="CCL">Coronary Catheter Laboratory</option>
			<option value="CCU">Coronary Care Unit</option>
			<option value="CDSA">Child Development Service South Akl</option>
			<option value="CHPN">Child Health/Public Health Nses Cl</option>
			<option value="COL">Colposcopy Clinic</option>
			<option value="COTT">The Cottage,</option>
			<option value="CPOD">C-POD KIDZ FIRST MEDICAL</option>
			<option value="CR">Child Respite Service</option>
			<option value="CRH">CARDIAC REHAB</option>
			<option value="CRT">Community based Rehabiliation Team</option>
			<option value="CSDU">Coronary Care Stepdown Unit</option>
			<option value="CSSD">Central Sterile Supply Department</option>
			<option value="CTEC">Clinical Training and Education Cen</option>
			<option value="CY&M">CHILD YOUTH AND MATERNITY</option>
			<option value="DCS">Discharge Community Supply</option>
			<option value="DCSA">Diabetes Centre South Auckland</option>
			<option value="DENT">Dental Clinic</option>
			<option value="DHB">District Health Board Counties Manu</option>
			<option value="DIAB">Diabetes Clinic Whitiora</option>
			<option value="DIAL">RENAL DIALYSIS RITO UNIT (MSC)</option>
			<option value="DIET">Nutrition Services (Dietitians)</option>
			<option value="DLHT">Home Training Renal Dialysis</option>
			<option value="DOU">Daily Operations Unit</option>
			<option value="ECAT">Assess & Treat Emergency Care</option>
			<option value="ECFT">EMERGENCY CARE FAST TRACK</option>
			<option value="ECMA">EC MEDICAL ASSESSMENT</option>
			<option value="ECMS">EC MEDICAL SHORT STAY (Level 1, EHB</option>
			<option value="ECMT">Monitored Emergency Care</option>
			<option value="ECSA">Surgical Assessment Unit</option>
			<option value="ECSS">Short Stay Emergency Care</option>
			<option value="EDGP">Emergency Department GP Clinic</option>
			<option value="ENGD">Engineering Department</option>
			<option value="ENT">Ear Nose and Throat Clinic</option>
			<option value="EOC">Emergency Operations Center (EOC)</option>
			<option value="EPAC">Early Pregnancy Assesment Centre</option>
			<option value="FALE">Faleola Services</option>
			<option value="FERC">Ferinject Clinic on ALBU North</option>
			<option value="FMH">Franklin Memorial Hospital</option>
			<option value="GAST">Gastroenterology Clinic</option>
			<option value="GCU">Gynaecology Care Unit</option>
			<option value="GCUN">Gynaecology Care Nursery</option>
			<option value="HAE">Haematology Day Ward</option>
			<option value="HBTN">Home Based Treatment North</option>
			<option value="HBTS">Home Based Treatment South</option>
			<option value="HCM">Midwives Home Care Service</option>
			<option value="HDU">High Dependency Unit</option>
			<option value="HEC">Hospital Exceptional Circumstances</option>
			<option value="HHHO">Howick Home Health Care (District N</option>
			<option value="HHPA">Papakura Home Healthcare Nurses</option>
			<option value="HHPU">Pukekohe Home Healthcare Nurses</option>
			<option value="HHSO">District Nurses, Southern</option>
			<option value="HPC">HPC (NPPA)</option>
			<option value="HUIA">HUIA, TIAHO MAI WARD</option>
			<option value="ICT">Community ICT & Early Intervention</option>
			<option value="ICUP">INTENSIVE CARE UNIT</option>
			<option value="IMH">Infant Mental Health</option>
			<option value="INA">Intake and Assessment</option>
			<option value="KFEC">KidzFirst Emergency Care</option>
			<option value="KFGM">Kidz First Grup Management</option>
			<option value="KFHC">KidzFirst Home Care</option>
			<option value="KFMC">KidzFirst Medical Care</option>
			<option value="KFPH">KIDZ FIRST PUBLIC HEALTH NURSES</option>
			<option value="KFSC">KidzFirst Surgical Care</option>
			<option value="KUA">Kuaka, Tiaho Mai</option>
			<option value="LAB">Laboratory</option>
			<option value="MAD">Maternity Administration Department</option>
			<option value="MAMM">Mammography Clinic</option>
			<option value="MANA">MANA KIDZ</option>
			<option value="MANU">Manufacturing</option>
			<option value="MATN">Maternity Ward - North</option>
			<option value="MATS">Maternity Ward - South</option>
			<option value="MCMH">Manukau Community Mental Health</option>
			<option value="MHA">MSC Hand Therapy, Module 5</option>
			<option value="MHSP">Mental Health Services Older People</option>
			<option value="MHT">Manukau Health Trust</option>
			<option value="MNCH">MANCHESTER SEE & TREAT UNIT</option>
			<option value="MNCO">Mangere Community Office- PHN's</option>
			<option value="MOD3">Manukau Superclinic Module 3</option>
			<option value="MOD4">Manukau Superclinic, Module 4</option>
			<option value="MOD5">Manukau Superclinic, Module 5</option>
			<option value="MOD6">Manukau Superclinic , Module 6</option>
			<option value="MOD7">Manukau Superclinic Module Seven</option>
			<option value="MOD8">Manukau Superclinic, Module 8</option>
			<option value="MOD9">Manukau Superclinic, Module 9</option>
			<option value="MRET">MIDDLEMORE RETAIL PHARMACY</option>
			<option value="MS10">MSC Module 10 - WOMEN'S HEALTH</option>
			<option value="MSC1">Manukau Superclinic Module 1</option>
			<option value="MSC2">Manukau Superclinic Module 2</option>
			<option value="MSOP">Manukau Surgery Centre Op Theatre</option>
			<option value="MSTB">MSC PYXIS THEATRE BULK</option>
			<option value="MSW1">Manukau Surgery Centre FIRST FLOOR</option>
			<option value="MSW2">Manukau Surgery Centre 2nd Floor</option>
			<option value="NBC">National Burns Centre</option>
			<option value="NEPH">NEPHROCARE DIALYSIS UNIT (ASCOT)</option>
			<option value="NNU">Neonatal Unit</option>
			<option value="NSS">Non Social Security - Out Patients</option>
			<option value="NUIE">NUEI Island</option>
			<option value="OH">Occupational Health</option>
			<option value="OPSV">OPTHALMOLOGY SERVICES MSC</option>
			<option value="OPTH">Ophthalmology Surgery Clinic</option>
			<option value="OPVA">OPIVA (Home IV)</option>
			<option value="ORTH">Orthopaedic Surgery</option>
			<option value="OT">Occupational Therapy</option>
			<option value="OTCO">Otara Community Office</option>
			<option value="PACH">PACIFIC HEALTH DIVISION</option>
			<option value="PACOP">OPTHALMOLOGY- PACU</option>
			<option value="PACU">Post Anaesthetic Care Unit</option>
			<option value="PAPN">PAPAKURA PUBLIC HEALTH NURSES</option>
			<option value="PAPO">Papakura Obstetric Hospital</option>
			<option value="PCT">Pharmaceutical CT</option>
			<option value="PCU">MSC Peri-Operative Care Unit</option>
			<option value="PGH">Pukekohe Aged Care Hospital</option>
			<option value="PHOT">Photography Department</option>
			<option value="PLAS">Plastics Clinic</option>
			<option value="PLNK">Plunket Nurses Lambie Drive</option>
			<option value="PNMA">Public Health Nurses, Clendon (shp)</option>
			<option value="POAC">POAC-Primary Options for Acute Care</option>
			<option value="PPHN">Public Health Nurses, Pukekohe</option>
			<option value="PRIM">PRIMA TRIAL</option>
			<option value="PROB">Problems with Stock - Supervisors</option>
			<option value="PT">Physiotherapy Department</option>
			<option value="PUKO">Pukekohe Obstetric Hospital</option>
			<option value="PVP">PUBLIC VACCINATION PROGRAMME, MSC</option>
			<option value="RAD">Radiology</option>
			<option value="RENA">Renal Incentre AMC</option>
			<option value="REQ">REPACK TO BULK</option>
			<option value="RESP">Respiratory Rehab</option>
			<option value="RHUM">rhuMAb 2H7 Trial</option>
			<option value="RIT2">RITO 2 - Western Campus Dialysis</option>
			<option value="RITIX">RITIXAMAB RETREATMENT TRIAL</option>
			<option value="ROND">RON DUNHAM (CORPORATE)</option>
			<option value="SADJ">Stock In - Stock Out</option>
			<option value="SCDU">Renal Dialysis SATELLITE Unit (MSC)</option>
			<option value="SMOK">Smoke Free Programme</option>
			<option value="SPA">SPINAL UNIT</option>
			<option value="SSC">Security Services</option>
			<option value="STKT">StockTake Adjustment</option>
			<option value="SUND">Sundry - Use For Obscure Department</option>
			<option value="TADU">Theatre Admission & Discharge Unit</option>
			<option value="TEST">TEST WARD FOR ACCEPTANCE TESTING</option>
			<option value="THA">THEATRE BULK POD1 and 2</option>
			<option value="THAI">PACU-POD3 (Bulk Store Hybrid)</option>
			<option value="THOT">OPERATING THEATRES (MMH)</option>
			<option value="THR">Theatre CSB PACU (Recovery)</option>
			<option value="TOR">Tamaki Oranga Recovery</option>
			<option value="TPW">Te Puna Waiora (Maori Mental Health</option>
			<option value="TRCT">Te Rawhiti Crisis Team,Highland P</option>
			<option value="TRI">Clinical Trials</option>
			<option value="TUI">Tui, Tiaho Mai</option>
			<option value="UA">Urgent Assessment (NPPA)</option>
			<option value="UOA">University of Auckland, Middlemore</option>
			<option value="VHIU">VERY HIGH INTENSITY USERS</option>
			<option value="WHDR">Women's Health Doctors (Obst & Gyn)</option>
			<option value="WHIR">WHIRINAKI (formerly Campbell Lodge)</option>
			<option value="WIRI">WIRI SCHOOLS</option>
			<option value="WVAC">WINTER VACCINE CLINIC</option>
			<option value="YH">Centre for Youth Health</option>

  			</select>
  			<input type="submit" value="Filter By Ward">
			</form>